### ISSUE TITLE
多卡训练卡住

### ISSUE THREAD

**Issue by ZDYoung0519** [InternLM/xtuner#1037]
我在用xtuner训练LLaVA时卡住。
在原先的4090Ti服务器上可以正常运行，迁移到2xA100上后，单卡训练正常，但多卡训练卡住

启动命令
```
CUDA_VISIBLE_DEVICES=3,4 NPROC_PER_NODE=$NGPUS xtuner train  ./gcl_llava/configs/$EXP_NAME/ScienceQA.py  --deepspeed deepspeed_zero2
```
期间GPU3,4的使用率UTL为100%，但一直没有训练进度，显存占用也只有3-5%左右.
而且我发先kill掉程序后，重新运行，会卡在
```
06/23 22:02:44 - mmengine - INFO - xtuner_dataset_timeout = 1:00:00
```

以下是完整输出：
```
> tuner) root@42e9cd112589:/data/GCL-MLLM# CUDA_VISIBLE_DEVICES=3,4 NPROC_PER_NODE=$NGPUS xtuner train  ./gcl_llava/configs/$EXP_NAME/ScienceQA.py \
06/23 21:57:09 - mmengine - WARNING - Use random port: 29089
[2025-06-23 21:57:11,045] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
W0623 21:57:15.608425 9360 site-packages/torch/distributed/run.py:792] 
W0623 21:57:15.608425 9360 site-packages/torch/distributed/run.py:792] *****************************************
W0623 21:57:15.608425 9360 site-packages/torch/distributed/run.py:792] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0623 21:57:15.608425 9360 site-packages/torch/distributed/run.py:792] *****************************************
[2025-06-23 21:57:19,131] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-06-23 21:57:19,211] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/root/anaconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/utils/dl_utils/setup_env.py:56: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
/root/anaconda3/envs/xtuner/lib/python3.10/site-packages/mmengine/utils/dl_utils/setup_env.py:56: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
06/23 21:57:23 - mmengine - INFO - 
------------------------------------------------------------
System environment:
    sys.platform: linux
    Python: 3.10.4 (main, Mar 31 2022, 08:41:55) [GCC 7.5.0]
    CUDA available: True
    MUSA available: False
    numpy_random_seed: 2025
    GPU 0,1: NVIDIA A100-PCIE-40GB
    CUDA_HOME: /usr/local/cuda
    NVCC: Cuda compilation tools, release 12.9, V12.9.86
    GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
    PyTorch: 2.6.0+cu124
    PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2024.2-Product Build 20240605 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.5.3 (Git Hash 66f0cb9eb66affd2da3bf5f8d897376f04aae6af)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 12.4
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 90.1
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, COMMIT_SHA=2236df1770800ffea5697b11b0bb0d910b2e59e1, CUDA_VERSION=12.4, CUDNN_VERSION=9.1.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DLIBKINETO_NOXPUPTI=ON -DUSE_FBGEMM -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, TORCH_VERSION=2.6.0, USE_CUDA=ON, USE_CUDNN=ON, USE_CUSPARSELT=1, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_GLOO=ON, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF, 

    TorchVision: 0.21.0+cu124
    OpenCV: 4.11.0
    MMEngine: 0.10.6

Runtime environment:
    cudnn_benchmark: False
    mp_cfg: {'mp_start_method': 'fork', 'opencv_num_threads': 0}
    dist_cfg: {'backend': 'nccl'}
    seed: 2025
    deterministic: False
    Distributed launcher: pytorch
    Distributed training: True
    GPU number: 2
------------------------------------------------------------

06/23 21:57:24 - mmengine - INFO - Config:
SYSTEM = ''
accumulative_counts = 1
batch_size = 8
betas = (
    0.9,
    0.999,
)
custom_hooks = [
    dict(
        tokenizer=dict(
            padding_side='right',
            pretrained_model_name_or_path='lmsys/vicuna-7b-v1.5',
            trust_remote_code=True,
            type='transformers.AutoTokenizer.from_pretrained'),
        type='xtuner.engine.hooks.DatasetInfoHook'),
]
data_path = '/data/public_datasets/COIN/Instructions_Original/ScienceQA/train.json'
data_root = '/data/public_datasets/COIN/'
dataloader_num_workers = 4
default_hooks = dict(
    checkpoint=dict(
        by_epoch=False,
        interval=100,
        max_keep_ckpts=-1,
        type='mmengine.hooks.CheckpointHook'),
    logger=dict(
        interval=1,
        log_metric_by_epoch=False,
        type='mmengine.hooks.LoggerHook'),
    param_scheduler=dict(type='mmengine.hooks.ParamSchedulerHook'),
    sampler_seed=dict(type='mmengine.hooks.DistSamplerSeedHook'),
    timer=dict(type='mmengine.hooks.IterTimerHook'))
env_cfg = dict(
    cudnn_benchmark=False,
    dist_cfg=dict(backend='nccl'),
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0))
evaluation_freq = 100
exp_name = 'vicuna_7b_lora_clip_large'
image_folder = '/data/public_datasets/'
image_processor = dict(
    pretrained_model_name_or_path='openai/clip-vit-large-patch14-336',
    trust_remote_code=True,
    type='transformers.CLIPImageProcessor.from_pretrained')
instruction_types = 'Instructions_Original'
launcher = 'pytorch'
limit_num = 100
llava_dataset = dict(
    data_path=
    '/data/public_datasets/COIN/Instructions_Original/ScienceQA/train.json',
    dataset_map_fn='xtuner.dataset.map_fns.llava_map_fn',
    image_folder='/data/public_datasets/',
    image_processor=dict(
        pretrained_model_name_or_path='openai/clip-vit-large-patch14-336',
        trust_remote_code=True,
        type='transformers.CLIPImageProcessor.from_pretrained'),
    max_length=1472,
    pad_image_to_square=True,
    template_map_fn=dict(
        template='xtuner.utils.PROMPT_TEMPLATE.vicuna',
        type='xtuner.dataset.map_fns.template_map_fn_factory'),
    tokenizer=dict(
        padding_side='right',
        pretrained_model_name_or_path='lmsys/vicuna-7b-v1.5',
        trust_remote_code=True,
        type='transformers.AutoTokenizer.from_pretrained'),
    type='gcl_llava.dataset.GCLLLaVADataset')
llm_name_or_path = 'lmsys/vicuna-7b-v1.5'
load_from = None
log_level = 'INFO'
log_processor = dict(by_epoch=False)
lr = 0.0002
max_epochs = 1
max_length = 1472
max_norm = 1
model = dict(
    freeze_llm=True,
    freeze_visual_encoder=True,
    llm=dict(
        pretrained_model_name_or_path='lmsys/vicuna-7b-v1.5',
        torch_dtype='torch.float16',
        trust_remote_code=True,
        type='transformers.AutoModelForCausalLM.from_pretrained'),
    llm_lora=dict(
        bias='none',
        lora_alpha=256,
        lora_dropout=0.05,
        r=192,
        task_type='CAUSAL_LM',
        type='peft.LoraConfig'),
    pretrained_pth='./pretrained_weights/mm_projector_xtuner.pt',
    type='xtuner.model.LLaVAModel',
    visual_encoder=dict(
        pretrained_model_name_or_path='openai/clip-vit-large-patch14-336',
        type='transformers.CLIPVisionModel.from_pretrained'))
offline_processed_text_folder = '/data/public_datasets/COIN/Instructions_Original_processed_llava_vicuna_7b_v15/ScienceQA'
optim_type = 'torch.optim.AdamW'
optim_wrapper = dict(
    accumulative_counts=1,
    clip_grad=dict(error_if_nonfinite=False, max_norm=1),
    dtype='float16',
    loss_scale='dynamic',
    optimizer=dict(
        betas=(
            0.9,
            0.999,
        ),
        lr=0.0002,
        type='torch.optim.AdamW',
        weight_decay=0),
    paramwise_cfg=dict(
        custom_keys=dict({'projector.model': dict(lr_mult=0.1)})),
    type='mmengine.optim.AmpOptimWrapper')
param_scheduler = [
    dict(
        begin=0,
        by_epoch=True,
        convert_to_iter_based=True,
        end=0.03,
        start_factor=1e-05,
        type='mmengine.optim.LinearLR'),
    dict(
        begin=0.03,
        by_epoch=True,
        convert_to_iter_based=True,
        end=1,
        eta_min=0.0,
        type='mmengine.optim.CosineAnnealingLR'),
]
pretrained_pth = './pretrained_weights/mm_projector_xtuner.pt'
print_steps = 1
prompt_template = 'xtuner.utils.PROMPT_TEMPLATE.vicuna'
randomness = dict(deterministic=False, seed=2025)
resume = False
save_steps = 100
save_total_limit = -1
task_name = 'ScienceQA'
test_cfg = dict(type='xtuner.engine.runner.myloops.TestLoop')
test_dataloader = dict(
    batch_size=1,
    collate_fn=dict(type='xtuner.dataset.collate_fns.default_collate_fn'),
    dataset=dict(
        datasets=[
            dict(
                data_path=
                '/data/public_datasets/COIN//Instructions_Original/ScienceQA/test.json',
                image_folder='/data/public_datasets/',
                image_processor=dict(
                    pretrained_model_name_or_path=
                    'openai/clip-vit-large-patch14-336',
                    trust_remote_code=True,
                    type='transformers.CLIPImageProcessor.from_pretrained'),
                max_length=1472,
                pad_image_to_square=True,
                prompt_template='xtuner.utils.PROMPT_TEMPLATE.vicuna',
                system='',
                tokenizer=dict(
                    padding_side='right',
                    pretrained_model_name_or_path='lmsys/vicuna-7b-v1.5',
                    trust_remote_code=True,
                    type='transformers.AutoTokenizer.from_pretrained'),
                type='gcl_llava.dataset.evaluation.ScienceQADataset'),
            dict(
                data_path=
                '/data/public_datasets/COIN//Instructions_Original/TextVQA/val.json',
                image_folder='/data/public_datasets/',
                image_processor=dict(
                    pretrained_model_name_or_path=
                    'openai/clip-vit-large-patch14-336',
                    trust_remote_code=True,
                    type='transformers.CLIPImageProcessor.from_pretrained'),
                max_length=1472,
                pad_image_to_square=True,
                prompt_template='xtuner.utils.PROMPT_TEMPLATE.vicuna',
                system='',
                tokenizer=dict(
                    padding_side='right',
                    pretrained_model_name_or_path='lmsys/vicuna-7b-v1.5',
                    trust_remote_code=True,
                    type='transformers.AutoTokenizer.from_pretrained'),
                type='gcl_llava.dataset.evaluation.TextVQADataset'),
        ],
        type='xtuner.dataset.ConcatDataset'),
    drop_last=False,
    num_workers=0,
    sampler=dict(shuffle=False, type='mmengine.dataset.DefaultSampler'))
test_dataset = [
    dict(
        data_path=
        '/data/public_datasets/COIN//Instructions_Original/ScienceQA/test.json',
        image_folder='/data/public_datasets/',
        image_processor=dict(
            pretrained_model_name_or_path='openai/clip-vit-large-patch14-336',
            trust_remote_code=True,
            type='transformers.CLIPImageProcessor.from_pretrained'),
        max_length=1472,
        pad_image_to_square=True,
        prompt_template='xtuner.utils.PROMPT_TEMPLATE.vicuna',
        system='',
        tokenizer=dict(
            padding_side='right',
            pretrained_model_name_or_path='lmsys/vicuna-7b-v1.5',
            trust_remote_code=True,
            type='transformers.AutoTokenizer.from_pretrained'),
        type='gcl_llava.dataset.evaluation.ScienceQADataset'),
    dict(
        data_path=
        '/data/public_datasets/COIN//Instructions_Original/TextVQA/val.json',
        image_folder='/data/public_datasets/',
        image_processor=dict(
            pretrained_model_name_or_path='openai/clip-vit-large-patch14-336',
            trust_remote_code=True,
            type='transformers.CLIPImageProcessor.from_pretrained'),
        max_length=1472,
        pad_image_to_square=True,
        prompt_template='xtuner.utils.PROMPT_TEMPLATE.vicuna',
        system='',
        tokenizer=dict(
            padding_side='right',
            pretrained_model_name_or_path='lmsys/vicuna-7b-v1.5',
            trust_remote_code=True,
            type='transformers.AutoTokenizer.from_pretrained'),
        type='gcl_llava.dataset.evaluation.TextVQADataset'),
]
test_evaluator = dict()
tokenizer = dict(
    padding_side='right',
    pretrained_model_name_or_path='lmsys/vicuna-7b-v1.5',
    trust_remote_code=True,
    type='transformers.AutoTokenizer.from_pretrained')
train_cfg = dict(max_epochs=1, type='xtuner.engine.runner.myloops.TrainLoop')
train_dataloader = dict(
    batch_size=8,
    collate_fn=dict(type='xtuner.dataset.collate_fns.default_collate_fn'),
    dataset=dict(
        data_path=
        '/data/public_datasets/COIN/Instructions_Original/ScienceQA/train.json',
        dataset_map_fn='xtuner.dataset.map_fns.llava_map_fn',
        image_folder='/data/public_datasets/',
        image_processor=dict(
            pretrained_model_name_or_path='openai/clip-vit-large-patch14-336',
            trust_remote_code=True,
            type='transformers.CLIPImageProcessor.from_pretrained'),
        max_length=1472,
        pad_image_to_square=True,
        template_map_fn=dict(
            template='xtuner.utils.PROMPT_TEMPLATE.vicuna',
            type='xtuner.dataset.map_fns.template_map_fn_factory'),
        tokenizer=dict(
            padding_side='right',
            pretrained_model_name_or_path='lmsys/vicuna-7b-v1.5',
            trust_remote_code=True,
            type='transformers.AutoTokenizer.from_pretrained'),
        type='gcl_llava.dataset.GCLLLaVADataset'),
    num_workers=4,
    pin_memory=True,
    sampler=dict(
        length_property='modality_length',
        per_device_batch_size=8,
        type='xtuner.dataset.samplers.LengthGroupedSampler'))
train_dataset = None
val_dataset = None
val_loader = None
visual_encoder_name_or_path = 'openai/clip-vit-large-patch14-336'
visualizer = dict(
    type='mmengine.visualization.Visualizer',
    vis_backends=[
        dict(
            init_kwargs=dict(
                experiment_name='vicuna_7b_lora_clip_large/ScienceQA',
                project='gcl-llava'),
            type='swanlab.integration.mmengine.SwanlabVisBackend'),
    ])
warmup_ratio = 0.03
weight_decay = 0
work_dir = './work_dirs/vicuna_7b_lora_clip_large/ScienceQA'

swanlab: Tracking run with swanlab version 0.6.4                                                    
swanlab: Run data will be saved locally in /data/GCL-MLLM/work_dirs/vicuna_7b_lora_clip_large/ScienceQA/20250623_215722/vis_data/run-20250623_215726-669f99ff
swanlab: 👋 Hi a806032098, welcome to swanlab!
swanlab: Syncing run vicuna_7b_lora_clip_large/ScienceQA to the cloud
swanlab: 🏠 View project at https://swanlab.cn/@a806032098/gcl-llava
swanlab: 🚀 View run at https://swanlab.cn/@a806032098/gcl-llava/runs/17857sp5p1jfnawt9yede
06/23 21:57:27 - mmengine - WARNING - Failed to search registry with scope "mmengine" in the "builder" registry tree. As a workaround, the current "builder" registry in "xtuner" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmengine" is a correct scope, or whether the registry is initialized.
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  3.99it/s]
/root/anaconda3/envs/xtuner/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/root/anaconda3/envs/xtuner/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:633: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/root/anaconda3/envs/xtuner/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/root/anaconda3/envs/xtuner/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:633: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
You are using an old version of the checkpointing format that is deprecated (We will also silently ignore `gradient_checkpointing_kwargs` in case you passed it).Please update to the new format on your modeling file. To use the new format, you need to completely remove the definition of the method `_set_gradient_checkpointing` in your model.
06/23 21:57:50 - mmengine - INFO - Load pretrained weight from ./pretrained_weights/mm_projector_xtuner.pt
```
看别的issue说需要增大虚拟内存，这是否有关系？
在我们的A100服务器上，free -lh 输出如下
             total        used        free      shared  buff/cache   available
Mem:          503Gi        33Gi       322Gi       218Mi       147Gi       466Gi
Swap:            0B          0B          0B

**Comment by ZDYoung0519** [comment]
补充：当我不使用deepspeed策略时，我发现只有一个显卡的显存占用，另一个几乎没有

**Comment by ZDYoung0519** [comment]
问题好像已经解决了，可能是虚拟化的原因，设置export NCCL_P2P_DISABLE=1就可以正常启动了
