### ISSUE TITLE
使用slurm进行单机多卡微调，但是只有一张卡在工作

### ISSUE THREAD

**Issue by BambiSheng** [InternLM/xtuner#846]
我现在在4*A100（80G）的机器上对llama2_7b模型进行全参数微调，slurm命令如下：
`OMP_NUM_THREADS=8 srun  --partition=MoE  --mpi=pmi2  --job-name=chat  -c 32  --gres=gpu:4  --nodes=1  --ntasks-per-node=1  --kill-on-bad-exit=1  xtuner train ./llama2_7b_full.py --launcher slurm --deepspeed deepspeed_zero3`
但是在训练10step之后就会报OOM：
`[rank0]: torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.77 GiB. GPU`
检查发现训练过程中只有一块GPU上有显存占用，其余GPU的显存都是空的。请问应该如何解决？
配置文件`llama2_7b_full.py`如下：
```
# Copyright (c) OpenMMLab. All rights reserved.
import torch
from datasets import load_dataset, load_from_disk
from mmengine.dataset import DefaultSampler
from mmengine.hooks import (CheckpointHook, DistSamplerSeedHook, IterTimerHook,
                            LoggerHook, ParamSchedulerHook)
from mmengine.optim import AmpOptimWrapper, CosineAnnealingLR, LinearLR
from peft import LoraConfig
from torch.optim import AdamW
from transformers import (AutoModelForCausalLM, AutoTokenizer,
                          BitsAndBytesConfig)

from xtuner.dataset import process_hf_dataset
from xtuner.dataset.collate_fns import default_collate_fn
from xtuner.dataset.map_fns import oasst1_map_fn, template_map_fn_factory
from xtuner.engine.hooks import (DatasetInfoHook, EvaluateChatHook,
                                 VarlenAttnArgsToMessageHubHook)
from xtuner.engine.runner import TrainLoop
from xtuner.model import SupervisedFinetune
from xtuner.parallel.sequence import SequenceParallelSampler
from xtuner.utils import PROMPT_TEMPLATE
from mmengine.visualization import Visualizer, WandbVisBackend

#######################################################################
#                          PART 1  Settings                           #
#######################################################################
# Model
pretrained_model_name_or_path = 'meta-llama/Llama-2-7b-hf'
use_varlen_attn = False

# Data
data_path = "./10k"
prompt_template = PROMPT_TEMPLATE.llama2_chat
max_length = 2048*4
pack_to_max_length = True

# parallel
sequence_parallel_size = 1

# Scheduler & Optimizer
batch_size = 1  # per_device
accumulative_counts = 16
accumulative_counts *= sequence_parallel_size
dataloader_num_workers = 0
max_epochs = 3
optim_type = AdamW
lr = 2e-4
betas = (0.9, 0.999)
weight_decay = 0
max_norm = 1  # grad clip
warmup_ratio = 0.03

# Save
save_steps = 10000
save_total_limit = 1  # Maximum checkpoints to keep (-1 means unlimited)

# Evaluate the generation performance during the training
evaluation_freq = 5000
SYSTEM = ''
evaluation_inputs = [
    '请给我介绍五个上海的景点', 'Please tell me five scenic spots in Shanghai'
]

#######################################################################
#                      PART 2  Model & Tokenizer                      #
#######################################################################
tokenizer = dict(
    type=AutoTokenizer.from_pretrained,
    pretrained_model_name_or_path=pretrained_model_name_or_path,
    trust_remote_code=True,
    padding_side='right')

model = dict(
    type=SupervisedFinetune,
    use_varlen_attn=use_varlen_attn,
    llm=dict(
        type=AutoModelForCausalLM.from_pretrained,
        pretrained_model_name_or_path=pretrained_model_name_or_path,
        torch_dtype=torch.float16
            )
)
#######################################################################
#                      PART 3  Dataset & Dataloader                   #
#######################################################################

def ultra_chat_map_fn(example):
    data = example['data']
    if len(data) % 2:
        data.pop()
    conversation = []
    for i in range(0, len(data), 2):
        single_turn_conversation = {'input': data[i], 'output': data[i + 1]}
        conversation.append(single_turn_conversation)
    return {'conversation': conversation}
train_dataset = dict(
    type=process_hf_dataset,
    dataset=dict(type=load_from_disk, dataset_path=data_path),
    tokenizer=tokenizer,
    max_length=max_length,
    dataset_map_fn=ultra_chat_map_fn,
    template_map_fn=dict(
        type=template_map_fn_factory, template=prompt_template),
    remove_unused_columns=True,
    shuffle_before_pack=True,
    pack_to_max_length=pack_to_max_length,
    use_varlen_attn=use_varlen_attn)

sampler = SequenceParallelSampler \
    if sequence_parallel_size > 1 else DefaultSampler
train_dataloader = dict(
    batch_size=batch_size,
    num_workers=dataloader_num_workers,
    dataset=train_dataset,
    sampler=dict(type=sampler, shuffle=True),
    collate_fn=dict(type=default_collate_fn, use_varlen_attn=use_varlen_attn))

#######################################################################
#                    PART 4  Scheduler & Optimizer                    #
#######################################################################
# optimizer
optim_wrapper = dict(
    type=AmpOptimWrapper,
    optimizer=dict(
        type=optim_type, lr=lr, betas=betas, weight_decay=weight_decay),
    clip_grad=dict(max_norm=max_norm, error_if_nonfinite=False),
    accumulative_counts=accumulative_counts,
    loss_scale='dynamic',
    dtype='float16')

# learning policy
# More information: https://github.com/open-mmlab/mmengine/blob/main/docs/en/tutorials/param_scheduler.md  # noqa: E501
param_scheduler = [
    dict(
        type=LinearLR,
        start_factor=1e-5,
        by_epoch=True,
        begin=0,
        end=warmup_ratio * max_epochs,
        convert_to_iter_based=True),
    dict(
        type=CosineAnnealingLR,
        eta_min=0.0,
        by_epoch=True,
        begin=warmup_ratio * max_epochs,
        end=max_epochs,
        convert_to_iter_based=True)
]

# train, val, test setting
train_cfg = dict(type=TrainLoop, max_epochs=max_epochs)

#######################################################################
#                           PART 5  Runtime                           #
#######################################################################
# Log the dialogue periodically during the training process, optional
custom_hooks = [
    dict(type=DatasetInfoHook, tokenizer=tokenizer),
    dict(
        type=EvaluateChatHook,
        tokenizer=tokenizer,
        every_n_iters=evaluation_freq,
        evaluation_inputs=evaluation_inputs,
        system=SYSTEM,
        prompt_template=prompt_template)
]

if use_varlen_attn:
    custom_hooks += [dict(type=VarlenAttnArgsToMessageHubHook)]

# configure default hooks
default_hooks = dict(
    # record the time of every iteration.
    timer=dict(type=IterTimerHook),
    # print log every 10 iterations.
    logger=dict(type=LoggerHook, log_metric_by_epoch=False, interval=10),
    # enable the parameter scheduler.
    param_scheduler=dict(type=ParamSchedulerHook),
    # save checkpoint per `save_steps`.
    checkpoint=dict(
        type=CheckpointHook,
        by_epoch=False,
        interval=save_steps,
        max_keep_ckpts=save_total_limit),
    # set sampler seed in distributed evrionment.
    sampler_seed=dict(type=DistSamplerSeedHook),
)

# configure environment
env_cfg = dict(
    # whether to enable cudnn benchmark
    cudnn_benchmark=False,
    # set multi process parameters
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0),
    # set distributed parameters
    dist_cfg=dict(backend='nccl'),
)

# set visualizer
visualizer = dict(type=Visualizer, vis_backends=[dict(type=WandbVisBackend)])

# set log level
log_level = 'INFO'

# load from which checkpoint
load_from = None

# whether to resume training from the loaded checkpoint
resume = False

# Defaults to use random seed and disable `deterministic`
randomness = dict(seed=None, deterministic=False)

# set log processor
log_processor = dict(by_epoch=False)

```

**Comment by HIT-cwh** [comment]
试一下这个命令呢？
```
srun -p MoE --job-name=xx --quotatype=auto --gres=gpu:4 --ntasks=4 --ntasks-per-node=4 --cpus-per-task=16 --kill-on-bad-exit=1 xtuner train ./llama2_7b_full.py --launcher slurm --deepspeed deepspeed_zero3
```

之后观察log中这里是否打印的是 4

![image](https://github.com/user-attachments/assets/88749167-ece5-4d52-b275-f07e1d7b00cc)

**Comment by BambiSheng** [comment]
> 试一下这个命令呢？
> 
> ```
> srun -p MoE --job-name=xx --quotatype=auto --gres=gpu:4 --ntasks=4 --ntasks-per-node=4 --cpus-per-task=16 --kill-on-bad-exit=1 xtuner train ./llama2_7b_full.py --launcher slurm --deepspeed deepspeed_zero3
> ```
> 
> 之后观察log中这里是否打印的是 4
> 
> ![image](https://private-user-images.githubusercontent.com/41630003/349494068-88749167-ece5-4d52-b275-f07e1d7b00cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMjQwMDEsIm5iZiI6MTcyMTIyMzcwMSwicGF0aCI6Ii80MTYzMDAwMy8zNDk0OTQwNjgtODg3NDkxNjctZWNlNS00ZDUyLWIyNzUtZjA3ZTFkN2IwMGNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDEzNDE0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiYTllOGYwY2Y2MzhhNzc2YjUyNjJlYmMwODVhNjRjMjUwYzg1MjkyOWVhNTQxMGMzODI1MzZhOWY5MDA4MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5UnNFlHuw4krAuTRnx5Nuw6ngkYhryJhJzpmsNNo96o)

解决了，感谢您！
